//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA211115.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFA211115.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] joga {
            get {
                object obj = ResourceManager.GetObject("joga", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap joga_BG {
            get {
                object obj = ResourceManager.GetObject("joga_BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAGOK
        ///(&apos;Austen Holcomb&apos;, 0),
        ///(&apos;Ralphy Vega&apos;, 0),
        ///(&apos;Lee Horton&apos;, 1),
        ///(&apos;Kelan Fox&apos;, 0),
        ///(&apos;Kye Dickerson&apos;, 0),
        ///(&apos;Shyla Hicks&apos;, 1),
        ///(&apos;Aston Betts&apos;, 0),
        ///(&apos;Griffin Harding&apos;, 0),
        ///(&apos;Johnathan Xiong&apos;, 0),
        ///(&apos;Ema Salter&apos;, 1),
        ///(&apos;Roxanne Abbott&apos;, 0),
        ///(&apos;Cohen Delgado&apos;, 1),
        ///(&apos;Anika Bernard&apos;, 1),
        ///(&apos;Edgar Whitley&apos;, 0),
        ///(&apos;Demi-Leigh Marquez&apos;, 0),
        ///(&apos;Elana Luna&apos;, 0),
        ///(&apos;Muhammed West&apos;, 1),
        ///(&apos;Parker Coulson&apos;, 0),
        ///(&apos;Olive Terrell&apos;, 0),
        ///(&apos;Avneet Valenzuela&apos;, 0),
        ///(&apos;Luther Lake&apos;, 0),
        ///(&apos;Oluwatobiloba Franks&apos;, 1) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jogaDataRows {
            get {
                return ResourceManager.GetString("jogaDataRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private void LbOktatok_DrawItem(object sender, DrawItemEventArgs e)
        ///{
        ///	e.DrawBackground();
        ///	Graphics g = e.Graphics;
        ///	Brush brush = ((e.State &amp; DrawItemState.Selected) == DrawItemState.Selected) ?
        ///	Brushes.Orange : new SolidBrush(e.BackColor);
        ///	g.FillRectangle(brush, e.Bounds);
        ///	e.Graphics.DrawString(
        ///	(sender as ListBox).Items[e.Index].ToString(), e.Font, 
        ///		new SolidBrush(e.ForeColor), e.Bounds, StringFormat.GenericDefault);
        ///	e.DrawFocusRectangle();
        ///}.
        /// </summary>
        internal static string orangeSelectionColor {
            get {
                return ResourceManager.GetString("orangeSelectionColor", resourceCulture);
            }
        }
    }
}
